### ISSUE TITLE
--docker option does not work

### ISSUE THREAD

**Issue by tchinchow** [juliogonzalez/docker-postgresql#3]
There is some code that parse the "--docker" option in the `manage_images` script however it can never be used because the previous call to `getopt` does not include the 'docker' option.

-> need to add docker to the list of allowed long options in the call to getopt

Hope it helps...

P.S. BTW : why parsing options both manually and with getopt instead of using getopt all the way ?

**Comment by juliogonzalez** [comment]
> -> need to add docker to the list of allowed long options in the call to getopt

Right, there was a typo from when I added the podman support, as docker was going to still remain as the default. But I didn't remember to adapt `getopt`.

Fixed by #7 

> P.S. BTW : why parsing options both manually and with getopt instead of using getopt all the way ?

I am not sure what you mean? Getopt returns an array, which what the while parses.

But I will be happy to learn a more efficient way. Please feel free to submit a PR.
